# Generated by Django 4.2.4 on 2023-08-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Codes",
            fields=[
                (
                    "code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("content", models.CharField(max_length=50)),
            ],
        ),
    ]
