# Generated by Django 4.2.4 on 2023-08-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visualization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthSafetyCntView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("sc_code", models.CharField(max_length=20)),
                ("code_count", models.IntegerField()),
                ("content", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "month_safetycnt_view",
                "managed": False,
            },
        ),
    ]
