# Generated by Django 4.2.4 on 2023-08-23 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visualization", "0002_monthsafetycntview"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="monthsafetycntview",
            table="new_month_safetycnt_view",
        ),
    ]
