# Generated by Django 3.2 on 2023-08-25 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0003_alter_monthsafetycntview_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthSafetyCntView',
        ),
    ]
