# Generated by Django 3.2 on 2023-08-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0004_delete_monthsafetycntview'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthSafetyCntView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('code', models.CharField(max_length=20)),
                ('code_count', models.IntegerField()),
                ('content', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'new_month_safetycnt_view',
                'managed': False,
            },
        ),
    ]
