# Generated by Django 3.2 on 2023-08-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0005_monthsafetycntview'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalSFView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('월', models.IntegerField()),
                ('일', models.IntegerField()),
                ('정상_착용_인원', models.IntegerField()),
                ('정상_착용X_인원', models.IntegerField()),
            ],
            options={
                'db_table': 'normal_sf_view',
                'managed': False,
            },
        ),
    ]
