# Generated by Django 3.2 on 2023-08-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0006_normalsfview'),
    ]

    operations = [
        migrations.CreateModel(
            name='HgvCntView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('helmet', models.IntegerField()),
                ('goggle', models.IntegerField()),
                ('vest', models.IntegerField()),
            ],
            options={
                'db_table': 'hgv_cnt_view',
                'managed': False,
            },
        ),
    ]
