# Generated by Django 4.2.4 on 2023-08-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workers",
            name="wname",
            field=models.CharField(max_length=50),
        ),
    ]
