# Generated by Django 4.2.4 on 2023-08-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attend", "0002_alter_workers_wname"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendWorkersView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("w_id", models.IntegerField()),
            ],
            options={
                "db_table": "attend_workers_view",
                "managed": False,
            },
        ),
    ]
