# Generated by Django 4.2.4 on 2023-08-21 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attend", "0003_attendworkersview"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AttendWorkersView",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="w_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="attend.workers"
            ),
        ),
        migrations.AlterField(
            model_name="safety_check",
            name="att_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="attend.attendance"
            ),
        ),
        migrations.AlterField(
            model_name="safety_check",
            name="w_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="attend.workers"
            ),
        ),
    ]
