# Generated by Django 4.2.4 on 2023-08-22 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attend", "0004_delete_attendworkersview_alter_attendance_w_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="attend_time",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
