# Generated by Django 4.2.4 on 2023-08-22 02:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attend", "0005_alter_attendance_attend_time"),
        ("access", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="access",
            name="in_time",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="access",
            name="p_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="access.place"
            ),
        ),
        migrations.AlterField(
            model_name="access",
            name="w_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="attend.workers"
            ),
        ),
        migrations.AlterField(
            model_name="slack",
            name="p_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="access.place"
            ),
        ),
        migrations.AlterField(
            model_name="slack",
            name="slack_time",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
